# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"_\n\x12TransactionRequest\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x13\n\x0breceiver_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x11\n\tsignature\x18\x04 \x01(\x0c\">\n\x13TransactionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\"\'\n\rVerifyRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"2\n\x0eVerifyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"W\n\x12\x46uelPaymentRequest\x12\x1c\n\x14\x66uel_price_per_liter\x18\x01 \x01(\x01\x12\x0e\n\x06liters\x18\x02 \x01(\x01\x12\x13\n\x0bis_finished\x18\x03 \x01(\x08\"7\n\x13\x46uelPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf7\x01\n\x0ePaymentService\x12N\n\x11\x43reateTransaction\x12\x1b.payment.TransactionRequest\x1a\x1c.payment.TransactionResponse\x12\x44\n\x11VerifyTransaction\x12\x16.payment.VerifyRequest\x1a\x17.payment.VerifyResponse\x12O\n\x12ProcessFuelPayment\x12\x1b.payment.FuelPaymentRequest\x1a\x1c.payment.FuelPaymentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=26
  _globals['_TRANSACTIONREQUEST']._serialized_end=121
  _globals['_TRANSACTIONRESPONSE']._serialized_start=123
  _globals['_TRANSACTIONRESPONSE']._serialized_end=185
  _globals['_VERIFYREQUEST']._serialized_start=187
  _globals['_VERIFYREQUEST']._serialized_end=226
  _globals['_VERIFYRESPONSE']._serialized_start=228
  _globals['_VERIFYRESPONSE']._serialized_end=278
  _globals['_FUELPAYMENTREQUEST']._serialized_start=280
  _globals['_FUELPAYMENTREQUEST']._serialized_end=367
  _globals['_FUELPAYMENTRESPONSE']._serialized_start=369
  _globals['_FUELPAYMENTRESPONSE']._serialized_end=424
  _globals['_PAYMENTSERVICE']._serialized_start=427
  _globals['_PAYMENTSERVICE']._serialized_end=674
# @@protoc_insertion_point(module_scope)
